---
title: "SAMPLE"
author: "Yujia Luan"
date: "2023-08-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}


fieller_SN1 <- fieller_child_df(chdf2010, "Senegal", "2010")
fieller_SN2 <- fieller_child_df(chdf2012, "Senegal", "2012")
fieller_SN3 <- fieller_child_df(chdf2014, "Senegal", "2014")
fieller_SN4 <- fieller_child_df(chdf2015, "Senegal", "2015")
fieller_SN5 <- fieller_child_df(chdf2016, "Senegal", "2016")
fieller_SN6 <- fieller_child_df(chdf2017, "Senegal", "2017")
fieller_SN7 <- fieller_child_df(chdf2018, "Senegal", "2018")
fieller_SN8 <- fieller_child_df(chdf2019, "Senegal", "2019")
fieller_SN <- rbind(fieller_SN1, fieller_SN2, fieller_SN3, fieller_SN4,fieller_SN5, fieller_SN6, fieller_SN7, fieller_SN8)
save(fieller_SN,file="fieller_SN.Rda")
```

```{r}
df_child <- rbind(df_child_lfix(chdf2010, "Senegal", "2010", 1,1,1,1),
                  df_child_lfix(chdf2012, "Senegal", "2012", 1,2,1,1),
                  df_child_lfix(chdf2014, "Senegal", "2014", 2,2,1,1),
                  df_child_lfix(chdf2015, "Senegal", "2015", 1,1,1,1),
                  df_child_lfix(chdf2016, "Senegal", "2016", 2,2,1,1),
                  df_child_lfix(chdf2017, "Senegal", "2017", 2,2,1,1),
                  df_child_lfix(chdf2018, "Senegal", "2018", 2,1,1,0),
                  df_child_lfix(chdf2019, "Senegal", "2019", 2,1,1,0))

fieller_fix_SN <- rbind(df_child)
save(fieller_fix_SN,file="fieller_fix_SN.Rda")
```

```{r}
nrow(chdf2019[chdf2019$hv105>4&chdf2019$hv105<16,])
nrow(chdf2019[chdf2019$hv105>15&chdf2019$hv105<18,])
nrow(chdf2019[chdf2019$hv105<18,])
```

```{r}
allyear_chdf<-list(chdf2005,chdf2010,chdf2012,chdf2014,chdf2015,chdf2016,chdf2017,chdf2018,chdf2019)
sample<-NULL
for (x in 1:9){
  chdf<-data.frame(allyear_chdf[x])
  a<-nrow(subset(chdf,chdf$hv105<18))
  b<-nrow(subset(chdf,chdf$hv105<5))
  c<-nrow(subset(chdf,chdf$hv105>4&chdf$hv105<16))
  d<-nrow(subset(chdf,chdf$hv105>15&chdf$hv105<18))
  print(c(a,b,c,d))
  sample<-cbind(sample_orphan,c(a,b,c,d))
}
save(sample,file="sample.csv")

```

```{r}
sample_orphan<-NULL
for (x in 1:9){
  chdf<-data.frame(allyear_chdf[x])
  a<-nrow(subset(chdf,chdf$hv105<18&chdf$Orphanhood=="orphan"))
  b<-nrow(subset(chdf,chdf$hv105<5&chdf$Orphanhood=="orphan"))
  c<-nrow(subset(chdf,chdf$hv105>4&chdf$hv105<16&chdf$Orphanhood=="orphan"))
  d<-nrow(subset(chdf,chdf$hv105>15&chdf$hv105<18&chdf$Orphanhood=="orphan"))
  print(c(a,b,c,d))
  sample_orphan<-cbind(sample_orphan,c(a,b,c,d))
}
save(sample_orphan,file="sample_orphan.csv")
```
```{r}
write.csv(Samplesize, "/Users/yujialuan/Desktop/UROP/Samplesize_SN.csv", row.names=FALSE)
Sampleorphan<-data.frame(sample_orphan)
write.csv(Sampleorphan, "/Users/yujialuan/Desktop/UROP/Sampleorphan_SN.csv", row.names=FALSE)
```

```{r}
chdf2005<-chdf2005 %>% drop_na("hv001","hv002","hv105","hvidx","Orphanhood")
chdf2010<-chdf2010 %>% drop_na("hv001","hv002","hv105","hvidx","Orphanhood")
chdf2012<-chdf2012 %>% drop_na("hv001","hv002","hv105","hvidx","Orphanhood")
chdf2014<-chdf2014 %>% drop_na("hv001","hv002","hv105","hvidx","Orphanhood")
chdf2015<-chdf2015 %>% drop_na("hv001","hv002","hv105","hvidx","Orphanhood")
chdf2016<-chdf2016 %>% drop_na("hv001","hv002","hv105","hvidx","Orphanhood")
chdf2017<-chdf2017 %>% drop_na("hv001","hv002","hv105","hvidx","Orphanhood")
chdf2018<-chdf2018 %>% drop_na("hv001","hv002","hv105","hvidx","Orphanhood")
chdf2019<-chdf2019 %>% drop_na("hv001","hv002","hv105","hvidx","Orphanhood")
```


```{r}
year <- c("household", "household with orphan")
chdfhousehold <- data.frame(year)
chdf2019$Orphanhood[chdf2019$Orphanhood == "non-orphan"] <- NA
chdfhousehold$"2019" <- c(nrow(chdf2019 %>% distinct(hv001, hv002, .keep_all = TRUE)),
                         nrow(subset(chdf2019,is.na(chdf2019$Orphanhood)==FALSE) %>% distinct(hv001, hv002, .keep_all = TRUE)))
chdf2018$Orphanhood[chdf2018$Orphanhood == "non-orphan"] <- NA
chdfhousehold$"2018" <- c(nrow(chdf2018 %>% distinct(hv001, hv002, .keep_all = TRUE)),
                         nrow(subset(chdf2018,is.na(chdf2018$Orphanhood)==FALSE) %>% distinct(hv001, hv002, .keep_all = TRUE)))
chdf2017$Orphanhood[chdf2017$Orphanhood == "non-orphan"] <- NA
chdfhousehold$"2017" <- c(nrow(chdf2017 %>% distinct(hv001, hv002, .keep_all = TRUE)),
                         nrow(subset(chdf2017,is.na(chdf2017$Orphanhood)==FALSE) %>% distinct(hv001, hv002, .keep_all = TRUE)))
chdf2016$Orphanhood[chdf2016$Orphanhood == "non-orphan"] <- NA
chdfhousehold$"2016" <- c(nrow(chdf2016 %>% distinct(hv001, hv002, .keep_all = TRUE)),
                         nrow(subset(chdf2016,is.na(chdf2016$Orphanhood)==FALSE) %>% distinct(hv001, hv002, .keep_all = TRUE)))
chdf2015$Orphanhood[chdf2015$Orphanhood == "non-orphan"] <- NA
chdfhousehold$"2015" <- c(nrow(chdf2015 %>% distinct(hv001, hv002, .keep_all = TRUE)),
                         nrow(subset(chdf2015,is.na(chdf2015$Orphanhood)==FALSE) %>% distinct(hv001, hv002, .keep_all = TRUE)))
chdf2014$Orphanhood[chdf2014$Orphanhood == "non-orphan"] <- NA
chdfhousehold$"2014" <- c(nrow(chdf2014 %>% distinct(hv001, hv002, .keep_all = TRUE)),
                         nrow(subset(chdf2014,is.na(chdf2014$Orphanhood)==FALSE) %>% distinct(hv001, hv002, .keep_all = TRUE)))
chdf2012$Orphanhood[chdf2012$Orphanhood == "non-orphan"] <- NA
chdfhousehold$"2012" <- c(nrow(chdf2012 %>% distinct(hv001, hv002, .keep_all = TRUE)),
                         nrow(subset(chdf2012,is.na(chdf2012$Orphanhood)==FALSE) %>% distinct(hv001, hv002, .keep_all = TRUE)))
chdf2010$Orphanhood[chdf2010$Orphanhood == "non-orphan"] <- NA
chdfhousehold$"2010" <- c(nrow(chdf2010 %>% distinct(hv001, hv002, .keep_all = TRUE)),
                         nrow(subset(chdf2010,is.na(chdf2010$Orphanhood)==FALSE) %>% distinct(hv001, hv002, .keep_all = TRUE)))
chdf2005$Orphanhood[chdf2005$Orphanhood == "non-orphan"] <- NA
chdfhousehold$"2005" <- c(nrow(chdf2005 %>% distinct(hv001, hv002, .keep_all = TRUE)),
                         nrow(subset(chdf2005,is.na(chdf2005$Orphanhood)==FALSE) %>% distinct(hv001, hv002, .keep_all = TRUE)))
write.csv(chdfhousehold, "/Users/yujialuan/Desktop/UROP/chdfhousehold_SN.csv", row.names=FALSE)
```

```{r}
chdf2019$Orphanhood[is.na(chdf2019$Orphanhood)==TRUE] <- "non-orphan"
chdf2018$Orphanhood[is.na(chdf2018$Orphanhood)==TRUE] <- "non-orphan"
chdf2017$Orphanhood[is.na(chdf2017$Orphanhood)==TRUE] <- "non-orphan"
chdf2016$Orphanhood[is.na(chdf2016$Orphanhood)==TRUE] <- "non-orphan"
chdf2015$Orphanhood[is.na(chdf2015$Orphanhood)==TRUE] <- "non-orphan"
chdf2014$Orphanhood[is.na(chdf2014$Orphanhood)==TRUE] <- "non-orphan"
chdf2012$Orphanhood[is.na(chdf2012$Orphanhood)==TRUE] <- "non-orphan"
chdf2010$Orphanhood[is.na(chdf2010$Orphanhood)==TRUE] <- "non-orphan"
chdf2005$Orphanhood[is.na(chdf2005$Orphanhood)==TRUE] <- "non-orphan"
```


```{r}
save(chdf2005,file="chdf2005.Rda")
save(chdf2010,file="chdf2010.Rda")
save(chdf2012,file="chdf2012.Rda")
save(chdf2014,file="chdf2014.Rda")
save(chdf2015,file="chdf2015.Rda")
save(chdf2016,file="chdf2016.Rda")
save(chdf2017,file="chdf2017.Rda")
save(chdf2018,file="chdf2018.Rda")
save(chdf2019,file="chdf2019.Rda")
```


```

