---
title: "Senegal_Orphanhood_Analysis_2010"
author: "Yujia Luan"
date: "2023-07-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(ggplot2)
library(stringr)
```

```{r}
chdf05<-subset(SN10HM,hv105<18)
#ignore missing values
chdf05 <- chdf05[,colSums(is.na(chdf05))<nrow(chdf05)*0.8]
```

```{r}
chdf<-chdf05
opdf<-subset(chdf,chdf$hv111==0|chdf$hv113==0)
nopdf<-subset(chdf,chdf$hv111!=0&chdf$hv113!=0)
lmdf<-subset(chdf,chdf$hv111==0)
lfdf<-subset(chdf,chdf$hv113==0)
```

```{r}
#school attendence hv121
op1<-table(opdf$hv121)[2]/nrow(opdf)

nop1<-table(nopdf$hv121)[2]/nrow(nopdf)

lm1<-table(lmdf$hv121)[2]/nrow(lmdf)

lf1<-table(lfdf$hv121)[2]/nrow(lfdf)

```

```{r}
#rural/urban
op2<-table(opdf$hv025)[2]/nrow(opdf)

nop2<-table(nopdf$hv025)[2]/nrow(nopdf)

lm2<-table(lmdf$hv025)[2]/nrow(lmdf)

lf2<-table(lfdf$hv025)[2]/nrow(lfdf)


```

```{r}
#hv206 electricity
op3<-table(opdf$hv206)[2]/nrow(opdf)

nop3<-table(nopdf$hv206)[2]/nrow(nopdf)

lm3<-table(lmdf$hv206)[2]/nrow(lmdf)

lf3<-table(lfdf$hv206)[2]/nrow(lfdf)
```

```{r}
#radio 
op4<-table(opdf$hv207)[2]/nrow(opdf)

nop4<-table(nopdf$hv207)[2]/nrow(nopdf)

lm4<-table(lmdf$hv207)[2]/nrow(lmdf)

lf4<-table(lfdf$hv207)[2]/nrow(lfdf)
```

```{r}
#television
op5<-table(opdf$hv208)[2]/nrow(opdf)

nop5<-table(nopdf$hv208)[2]/nrow(nopdf)

lm5<-table(lmdf$hv208)[2]/nrow(lmdf)

lf5<-table(lfdf$hv208)[2]/nrow(lfdf)
```

```{r}
#refrigerator
op6<-table(opdf$hv209)[2]/nrow(opdf)

nop6<-table(nopdf$hv209)[2]/nrow(nopdf)

lm6<-table(lmdf$hv209)[2]/nrow(lmdf)

lf6<-table(lfdf$hv209)[2]/nrow(lfdf)
```

```{r}
#bicycle
op7<-table(opdf$hv210)[2]/nrow(opdf)

nop7<-table(nopdf$hv210)[2]/nrow(nopdf)

lm7<-table(lmdf$hv210)[2]/nrow(lmdf)

lf7<-table(lfdf$hv210)[2]/nrow(lfdf)
```


```{r}
# motor/scooter
op8<-table(opdf$hv211)[2]/nrow(opdf)

nop8<-table(nopdf$hv211)[2]/nrow(nopdf)

lm8<-table(lmdf$hv211)[2]/nrow(lmdf)

lf8<-table(lfdf$hv211)[2]/nrow(lfdf)
```

```{r}
#car
op9<-table(opdf$hv212)[2]/nrow(opdf)

nop9<-table(nopdf$hv212)[2]/nrow(nopdf)

lm9<-table(lmdf$hv212)[2]/nrow(lmdf)

lf9<-table(lfdf$hv212)[2]/nrow(lfdf)
```

```{r}
# phone
op10<-table(opdf$hv221)[2]/nrow(opdf)

nop10<-table(nopdf$hv221)[2]/nrow(nopdf)

lm10<-table(lmdf$hv221)[2]/nrow(lmdf)

lf10<-table(lfdf$hv221)[2]/nrow(lfdf)
```

```{r}
# bednet
op11<-table(opdf$hv227)[2]/nrow(opdf)

nop11<-table(nopdf$hv227)[2]/nrow(nopdf)

lm11<-table(lmdf$hv227)[2]/nrow(lmdf)

lf11<-table(lfdf$hv227)[2]/nrow(lfdf)
```


```{r}
df05features<-data.frame(proportion=c(op1,op2,op3,op4,op5,op6,op7,op8,op9,op10,op11,nop1,nop2,nop3,nop4,nop5,nop6,nop7,nop8,nop9,nop10,nop11,lm1,lm2,lm3,lm4,lm5,lm6,lm7,lm8,lm9,lm10,lm11,lf1,lf2,lf3,lf4,lf5,lf6,lf7,lf8,lf9,lf10,lf11),dataname=c("op1","op2","op3","op4","op5","op6","op7","op8","op9","op10","op11","nop1","nop2","nop3","nop4","nop5","nop6","nop7","nop8","nop9","nop10","nop11","lm1","lm2","lm3","lm4","lm5","lm6","lm7","lm8","lm9","lm10","lm11","lf1","lf2","lf3","lf4","lf5","lf6","lf7","lf8","lf9","lf10","lf11"))
```


```{r}
df05features["orphanhood"]<-integer(44)
for (x in 1:11){
  df05features$orphanhood[x]<-"orphan"
}
for (x in 12:22){
  df05features$orphanhood[x]<-"nonorphan"
}
for (x in 23:33){
  df05features$orphanhood[x]<-"lostmother"
}
for (x in 34:44){
  df05features$orphanhood[x]<-"lostfather"
}
for (x in 1:44){
  if (x%%11==10|x%%11==0){
    df05features$question[x]<-str_sub(df05features$dataname[x],-2,-1)
  }
  else{
    df05features$question[x]<-str_sub(df05features$dataname[x],-1,-1)
  }
}

```

```{r}
# function of confidence interval
CIupper<-function(x,n){
  upper<-x+1.96*sqrt(x*(1-x)/n)
  return(upper)
}

CIlower<-function(x,n){
  lower<-x-1.96*sqrt(x*(1-x)/n)
  return(lower)
}
```


```{r}
# confidence intervals upper
df05features["upper"]<-integer(44)
for (x in 1:11){
  df05features$upper[x]<-CIupper(df05features$proportion[x],nrow(opdf))
}
for (x in 12:22){
  df05features$upper[x]<-CIupper(df05features$proportion[x],nrow(nopdf))
}
for (x in 23:33){
  df05features$upper[x]<-CIupper(df05features$proportion[x],nrow(lmdf))
}
for (x in 34:44){
  df05features$upper[x]<-CIupper(df05features$proportion[x],nrow(lfdf))
}
# confidence intervals lower
df05features["lower"]<-integer(44)
for (x in 1:11){
  df05features$lower[x]<-CIlower(df05features$proportion[x],nrow(opdf))
}
for (x in 12:22){
  df05features$lower[x]<-CIlower(df05features$proportion[x],nrow(nopdf))
}
for (x in 23:33){
  df05features$lower[x]<-CIlower(df05features$proportion[x],nrow(lmdf))
}
for (x in 34:44){
  df05features$lower[x]<-CIlower(df05features$proportion[x],nrow(lfdf))
}
```

```{r}
#df05fea1<-subset(df05features,df05features)
df05features['question']<-c("school attendence","urban/rural","has electricity","has radio","has television","has refrigerator","has bicycle","has motorcycle","has car","has phone","has bednet","school attendence","urban/rural","has electricity","has radio","has television","has refrigerator","has bicycle","has motorcycle","has car","has phone","has bednet","school attendence","urban/rural","has electricity","has radio","has television","has refrigerator","has bicycle","has motorcycle","has car","has phone","has bednet","school attendence","urban/rural","has electricity","has radio","has television","has refrigerator","has bicycle","has motorcycle","has car","has phone","has bednet")
df05features<-subset(df05features,df05features$orphanhood=="orphan"|df05features$orphanhood=="nonorphan")
```


```{r}
# draw the barplot
binary05<-ggplot(data = df05features, mapping = aes(x=question,y = proportion, fill = orphanhood)) +
  geom_bar(stat = 'identity', position = 'dodge') + 
  geom_errorbar( aes(ymin=lower, ymax=upper), width=0.4, colour="orange", alpha=0.6,position = position_dodge(.9)) + 
  scale_fill_manual(values=c('#99FFFF','#66CCCC','#CCFFFF','#99CCFF')) + theme_bw() + theme(panel.grid=element_blank()) +
  coord_flip()+
  ggtitle("Senegal 2010")+
  theme(panel.border = element_blank())+
  labs(y="percentage",x="questions")
  
#'#CCFFFF','#99CCFF'
print(binary05)
```
Then we analyse the health condition of children under age 5 using BMI
```{r}

chdf05<-subset(SN05HM,hv105<5)
chdf05<-subset(chdf05,is.na(chdf05$hc2)==0&chdf05$hc2!=9999)
chdf05["BMI"]<-integer(nrow(chdf05))
chdf05["heightage"]<-integer(nrow(chdf05))
chdf05["weightage"]<-integer(nrow(chdf05))
for (x in 1:nrow(chdf05)){
  chdf05$BMI[x]<-(chdf05$hc2[x]/10)/(chdf05$hc3[x]/1000)**2
  chdf05$heightage[x]<-(chdf05$hc3[x]/1000)/(chdf05$hc1[x]/12)
  chdf05$weightage[x]<-(chdf05$hc2[x]/10)/(chdf05$hc1[x]/12)
}
for (x in 1:nrow(chdf05)){
  if (chdf05$hv111[x]==0|chdf05$hv113[x]==0){
    chdf05$orphanhood[x]<-"orphan"
  }
  else{
    chdf05$orphanhood[x]<-"nonorphan"
  }
}

```

```{r}
BMI05<-ggplot(data=chdf05,mapping=aes(x=orphanhood,y=BMI))+geom_boxplot()+ylim(c(5,35))+geom_boxplot(outlier.colour = "red", outlier.shape = 1)+
  coord_flip()+
  ggtitle("Senegal 2010(Children under 5)")+theme_bw()
print(BMI05)
```
here we can see there are outliers due to recording error
```{r}

```




