---
title: "Senegal_Orphanhood_Analysis_2019"
author: "Yujia Luan"
date: "2023-07-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#ignore missing information of household line number
SN19CH <- SN19CH[!is.na(SN19CH1$b16), ]
SN19CH<- SN19CH[SN19CH$b16!=0, ]
```


```{r}
#add a column of orphanhood info
SN19CH1["hv111"]<-NA
for (x in 1:5688){
  y<-SN19CH1$b16[x]
    if (y<10){
    col<-paste("hv111_0",as.character(y),sep="")
    }else{
    col<-paste("hv111_",as.character(y),sep="")
    }
    for (z in 1:4538){
      if (SN19HH$hv001[z]==SN19CH1$hv001[x]&SN19HH$hv002[z]==SN19CH1$hv002[x]){
         SN19CH1$hv111[x]<-SN19HH[[col]][z]
      }
    }
}
```

```{r}
#add another column of orphanhood info
SN19CH1["hv113"]<-NA
for (x in 1:5688){
  y<-SN19CH1$b16[x]
    if (y<10){
    col<-paste("hv113_0",as.character(y),sep="")
    }else{
    col<-paste("hv113_",as.character(y),sep="")
    }
    for (z in 1:4538){
      if (SN19HH$hv001[z]==SN19CH1$hv001[x]&SN19HH$hv002[z]==SN19CH1$hv002[x]){
         SN19CH1$hv113[x]<-SN19HH[[col]][z]
      }
    }
}
```


```{r}
#learn how lossing father affects the child
lfc<-subset(SN19CH1,hv113==0)
fc<-subset(SN19CH1,hv113==1)
table(lfc$h10)
table(fc$h10)
#a little data to analyse
```

```{r}
#extract children's information from household member data
chdf<-subset(SN19HM,hv105<18)
```

```{r}
#ignore missing information of hv111 and hv113
chdf <- chdf[,colSums(is.na(chdf))<nrow(chdf)]
#chdf <- na.omit(chdf[ , !(colnames(chdf) %in% "hv111")])
#chdf <- na.omit(chdf[ , !(colnames(chdf) %in% "hv113")])
```

```{r}
#dataframe of orphan and non-orphan
opdf<-subset(chdf,chdf$hv111==0|chdf$hv113==0)
nopdf<-subset(chdf,chdf$hv111!=0&chdf$hv113!=0)
lmdf<-subset(chdf,chdf$hv111==0)
lfdf<-subset(chdf,chdf$hv113==0)
fdf<-subset(chdf,chdf$hv104==2)
mdf<-subset(chdf,chdf$hv104==1)
fopdf<-subset(opdf,opdf$hv104==2)
mopdf<-subset(opdf,opdf$hv104==1)
```

If the children still attend schools in 2019
```{r}
#recode hv121

ch1<-table(chdf$hv121)[2]/nrow(chdf)

op1<-table(opdf$hv121)[2]/nrow(opdf)

nop1<-table(nopdf$hv121)[2]/nrow(nopdf)

lm1<-table(lmdf$hv121)[2]/nrow(lmdf)

lf1<-table(lfdf$hv121)[2]/nrow(lfdf)

f1<-table(fdf$hv121)[2]/nrow(fdf)

m1<-table(mdf$hv121)[2]/nrow(mdf)

fop1<-table(fopdf$hv121)[2]/nrow(fopdf)

mop1<-table(mopdf$hv121)[2]/nrow(mopdf)

hv121vec<-c(op1,nop1,lm1,lf1)
#draw a barplot of hv121 statistics
par(mar=c(3,3,3,3))
barplot(hv121vec,names.arg=c("op1","nop1","lm1","lf1"),main="hv121 chart",xlab="class",ylab="proportion",xlim=c(0,4),ylim=c(0,1))
```
```{r}
hv121vec<-c(ch1,f1,m1)
#draw a barplot of hv121 statistics
par(mar=c(3,3,3,3))
barplot(hv121vec,names.arg=c("ch1","f1","m1"),main="hv121 chart",xlab="class",ylab="proportion",xlim=c(0,4),ylim=c(0,1))
```
Net observed
```{r}
#recode hml3

ch1<-table(chdf$hml3)[2]/nrow(chdf)

op1<-table(opdf$hml3)[2]/nrow(opdf)

nop1<-table(nopdf$hml3)[2]/nrow(nopdf)

lm1<-table(lmdf$hml3)[2]/nrow(lmdf)

lf1<-table(lfdf$hml3)[2]/nrow(lfdf)


f1<-table(fdf$hml3)[2]/nrow(fdf)

m1<-table(mdf$hml3)[2]/nrow(mdf)

fop1<-table(fopdf$hml3)[2]/nrow(fopdf)

mop1<-table(mopdf$hml3)[2]/nrow(mopdf)

hml73vec<-c(op1,nop1,lm1,lf1)
#draw a barplot of hml73 statistics
par(mar=c(3,3,3,3))
barplot(hml73vec,names.arg=c("op1","nop1","lm1","lf1"),main="hml73 chart orphanhood",xlab="class",ylab="proportion",xlim=c(0,4),ylim=c(0,1))
```

```{r}
hml73vec<-c(ch1,f1,m1)
#draw a barplot of hml73 statistics
par(mar=c(3,3,3,3))
barplot(hml73vec,names.arg=c("ch1","f1","m1"),main="hml73 chart by gender",xlab="class",ylab="proportion",xlim=c(0,4),ylim=c(0,1))
```
health index
```{r}
op1<-table(opdf$hv270)[1]/nrow(opdf)
op2<-table(opdf$hv270)[2]/nrow(opdf)
op3<-table(opdf$hv270)[3]/nrow(opdf)
op4<-table(opdf$hv270)[4]/nrow(opdf)
op5<-table(opdf$hv270)[5]/nrow(opdf)
nop1<-table(nopdf$hv270)[1]/nrow(nopdf)
nop2<-table(nopdf$hv270)[2]/nrow(nopdf)
nop3<-table(nopdf$hv270)[3]/nrow(nopdf)
nop4<-table(nopdf$hv270)[4]/nrow(nopdf)
nop5<-table(nopdf$hv270)[5]/nrow(nopdf)

```

```{r}

mat1<-matrix(c(op1,op2,op3,op4,op5,nop1,nop2,nop3,nop4,nop5),nrow=2,ncol=5)
par(mar=c(5,5,5,5))
barplot(height=mat1,names.arg=c("poorest","poorer","middle","richer","richest"),main="hv270",xlab="class",ylab="proportion",beside=TRUE,ylim=c(0,1))


```



